from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, DateTime, Float
import pymysql
e
import settings

pymysql.install_as_MySQLdb()

user = settings.username
password = settings.password
host = settings.host
db_name = settings.db_name

# engineの設定
engine = create_engine(f'mysql://{user}:{password}@{host}/{db_name}')

SessionClass = sessionmaker(engine)  # セッションを作るクラスを作成
session = SessionClass()

# テーブルを作成する
Base = declarative_base()


class BaseOrderBook(object):
    q1 = Column(Float)
    q2 = Column(Float)
    q3 = Column(Float)
    q4 = Column(Float)
    q5 = Column(Float)
    q6 = Column(Float)
    q7 = Column(Float)
    q8 = Column(Float)
    q9 = Column(Float)
    q10 = Column(Float)
    q11 = Column(Float)
    q12 = Column(Float)
    q13 = Column(Float)
    q14 = Column(Float)
    q15 = Column(Float)
    q16 = Column(Float)
    q17 = Column(Float)
    q18 = Column(Float)
    q19 = Column(Float)
    q20 = Column(Float)
    q21 = Column(Float)
    q22 = Column(Float)
    q23 = Column(Float)
    q24 = Column(Float)
    q25 = Column(Float)
    q26 = Column(Float)
    q27 = Column(Float)
    q28 = Column(Float)
    q29 = Column(Float)
    q30 = Column(Float)
    q31 = Column(Float)
    q32 = Column(Float)
    q33 = Column(Float)
    q34 = Column(Float)
    q35 = Column(Float)
    q36 = Column(Float)
    q37 = Column(Float)
    q38 = Column(Float)
    q39 = Column(Float)
    q40 = Column(Float)
    q41 = Column(Float)
    q42 = Column(Float)
    q43 = Column(Float)
    q44 = Column(Float)
    q45 = Column(Float)
    q46 = Column(Float)
    q47 = Column(Float)
    q48 = Column(Float)
    q49 = Column(Float)
    q50 = Column(Float)
    q51 = Column(Float)
    q52 = Column(Float)
    q53 = Column(Float)
    q54 = Column(Float)
    q55 = Column(Float)
    q56 = Column(Float)
    q57 = Column(Float)
    q58 = Column(Float)
    q59 = Column(Float)
    q60 = Column(Float)
    q61 = Column(Float)
    q62 = Column(Float)
    q63 = Column(Float)
    q64 = Column(Float)
    q65 = Column(Float)
    q66 = Column(Float)
    q67 = Column(Float)
    q68 = Column(Float)
    q69 = Column(Float)
    q70 = Column(Float)
    q71 = Column(Float)
    q72 = Column(Float)
    q73 = Column(Float)
    q74 = Column(Float)
    q75 = Column(Float)
    q76 = Column(Float)
    q77 = Column(Float)
    q78 = Column(Float)
    q79 = Column(Float)
    q80 = Column(Float)
    q81 = Column(Float)
    q82 = Column(Float)
    q83 = Column(Float)
    q84 = Column(Float)
    q85 = Column(Float)
    q86 = Column(Float)
    q87 = Column(Float)
    q88 = Column(Float)
    q89 = Column(Float)
    q90 = Column(Float)
    q91 = Column(Float)
    q92 = Column(Float)
    q93 = Column(Float)
    q94 = Column(Float)
    q95 = Column(Float)
    q96 = Column(Float)
    q97 = Column(Float)
    q98 = Column(Float)
    q99 = Column(Float)
    q100 = Column(Float)
    q101 = Column(Float)
    q102 = Column(Float)
    q103 = Column(Float)
    q104 = Column(Float)
    q105 = Column(Float)
    q106 = Column(Float)
    q107 = Column(Float)
    q108 = Column(Float)
    q109 = Column(Float)
    q110 = Column(Float)
    q111 = Column(Float)
    q112 = Column(Float)
    q113 = Column(Float)
    q114 = Column(Float)
    q115 = Column(Float)
    q116 = Column(Float)
    q117 = Column(Float)
    q118 = Column(Float)
    q119 = Column(Float)
    q120 = Column(Float)
    q121 = Column(Float)
    q122 = Column(Float)
    q123 = Column(Float)
    q124 = Column(Float)
    q125 = Column(Float)
    q126 = Column(Float)
    q127 = Column(Float)
    q128 = Column(Float)
    q129 = Column(Float)
    q130 = Column(Float)
    q131 = Column(Float)
    q132 = Column(Float)
    q133 = Column(Float)
    q134 = Column(Float)
    q135 = Column(Float)
    q136 = Column(Float)
    q137 = Column(Float)
    q138 = Column(Float)
    q139 = Column(Float)
    q140 = Column(Float)
    q141 = Column(Float)
    q142 = Column(Float)
    q143 = Column(Float)
    q144 = Column(Float)
    q145 = Column(Float)
    q146 = Column(Float)
    q147 = Column(Float)
    q148 = Column(Float)
    q149 = Column(Float)
    q150 = Column(Float)
    q151 = Column(Float)
    q152 = Column(Float)
    q153 = Column(Float)
    q154 = Column(Float)
    q155 = Column(Float)
    q156 = Column(Float)
    q157 = Column(Float)
    q158 = Column(Float)
    q159 = Column(Float)
    q160 = Column(Float)
    q161 = Column(Float)
    q162 = Column(Float)
    q163 = Column(Float)
    q164 = Column(Float)
    q165 = Column(Float)
    q166 = Column(Float)
    q167 = Column(Float)
    q168 = Column(Float)
    q169 = Column(Float)
    q170 = Column(Float)
    q171 = Column(Float)
    q172 = Column(Float)
    q173 = Column(Float)
    q174 = Column(Float)
    q175 = Column(Float)
    q176 = Column(Float)
    q177 = Column(Float)
    q178 = Column(Float)
    q179 = Column(Float)
    q180 = Column(Float)
    q181 = Column(Float)
    q182 = Column(Float)
    q183 = Column(Float)
    q184 = Column(Float)
    q185 = Column(Float)
    q186 = Column(Float)
    q187 = Column(Float)
    q188 = Column(Float)
    q189 = Column(Float)
    q190 = Column(Float)
    q191 = Column(Float)
    q192 = Column(Float)
    q193 = Column(Float)
    q194 = Column(Float)
    q195 = Column(Float)
    q196 = Column(Float)
    q197 = Column(Float)
    q198 = Column(Float)
    q199 = Column(Float)
    q200 = Column(Float)
    timestamp = Column(DateTime, primary_key=True)


class BaseOrderPrice(BaseOrderBook):
    pass


class BaseOrderSize(BaseOrderBook):
    volume = Column(Float)


class AskPrice(BaseOrderPrice, Base):
    __tablename__ = 'ask_price'


class BidPrice(BaseOrderPrice, Base):
    __tablename__ = 'bid_price'


class AskSize(BaseOrderSize, Base):
    __tablename__ = 'ask_size'


class BidSize(BaseOrderSize, Base):
    __tablename__ = 'bid_size'


Base.metadata.create_all(bind=engine)

# db_session.add(BaseOrderBook(name='Tommmy', gender='Female', age=18, birthday='2003-12-9 09:09:32'))
# db_session.commit()

